In [1]:
import pandas as pd
import numpy as np
from glob import iglob

In [2]:
!ls ../DeepTrader/data/DJIA

data_fetch.ipynb  djia_stocks  djia_stocks.csv	industry_classification.npy

In [3]:
df_desp = pd.read_csv("../DeepTrader/data/DJIA/djia_stocks.csv")

In [4]:
data_fpath = [i for i in iglob("../DeepTrader/data/DJIA/djia_stocks/*.csv")]

In [5]:
df_stocks = pd.read_csv(data_fpath[1], index_col=0)

In [6]:
df_stocks

,Date,Open,Low,High,Close,Adj. Close,Volume,Shares Outstanding,Dividend Yield,Earnings Yield,FCF Yield,Market-Cap,P/Cash,P/E,P/FCF,P/NCAV,P/NetNet,P/Sales,Price to Book Value
0,2007-01-03,68.42,67.85,69.48,68.40,51.66,12908400,1.166000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2007-01-04,69.48,68.97,71.87,71.33,53.87,16000900,1.166000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2007-01-05,71.34,71.01,72.08,71.50,54.00,10462000,1.166000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2007-01-08,71.63,70.79,71.89,70.93,53.57,6747100,1.166000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2007-01-09,71.17,70.67,71.68,71.27,53.82,7165200,1.166000e+09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3985,2022-10-31,269.20,268.00,271.81,270.35,270.35,3031003,5.350000e+08,0.027985,0.046135,0.060728,1.481518e+11,12.907458,21.675465,16.466800,-4.117043,-3.511039,5.626730,40.556200
3986,2022-11-01,269.60,268.38,272.87,272.06,272.06,2062119,5.350000e+08,0.027809,0.045845,0.060347,1.490889e+11,12.989099,21.812565,16.570955,-4.143084,-3.533247,5.662320,40.812724
3987,2022-11-02,271.64,268.95,274.88,269.01,269.01,2636503,5.350000e+08,0.028124,0.046365,0.061031,1.474175e+11,12.843481,21.568029,16.385182,-4.096637,-3.493636,5.598841,40.355182
3988,2022-11-03,268.53,265.02,268.60,265.88,265.88,2764696,5.350000e+08,0.028455,0.046911,0.061749,1.457022e+11,12.694044,21.317080,16.194536,-4.048972,-3.452987,5.533697,39.885639
3989,2022-11-04,261.94,259.84,269.30,269.04,269.04,3401263,5.350000e+08,0.028121,0.046360,0.061024,1.474339e+11,12.844914,21.570435,16.387009,-4.097094,-3.494026,5.599465,40.359682

In [7]:
df_stocks["Shares Outstanding"].isna().sum() / df_stocks["Shares Outstanding"].size

0.0